"""admin_comment

Revision ID: 73d5c6101d0c
Revises: 3142ebd16337
Create Date: 2026-03-07 09:10:01.865320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d5c6101d0c'
down_revision: Union[str, None] = '3142ebd16337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_comment')
    # ### end Alembic commands ###
