"""disabled user

Revision ID: 1d905becb4ec
Revises: 3142ebd16337
Create Date: 2026-03-07 09:38:11.723235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d905becb4ec'
down_revision: Union[str, None] = '3142ebd16337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_comment', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'admin_comment')
    # ### end Alembic commands ###
