"""add discord_id to user and make password nullable

Revision ID: 3142ebd16337
Revises: 09430ff72f79
Create Date: 2026-03-03 19:48:00.219651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3142ebd16337'
down_revision: Union[str, None] = '09430ff72f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('discord_id', sa.String(length=32), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('discord_id_idx', 'user', ['discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discord_id_idx', 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'discord_id')
    # ### end Alembic commands ###
